
pages:
  image: debian:buster
  script:
    - apt-get update
    - apt-get -qy install --no-install-recommends lektor
    - test -d public || mkdir public
    - printf "The Tor Project\n\n\n" | lektor quickstart --name "torspec" --path tmp
    - rm -rf tmp/content/*
    - mv tmp/* .
    - sed 's,^ *\[[^\]]*\]?.$,,' templates/layout.html # delete unused menu items
    - printf "title\x3a $CI_PROJECT_PATH\n---\nbody:\n\n" > content/contents.lr
    - for f in *.txt; do
        set -x;
        name=`echo $f | sed s,\.txt$,,`;
        md=${name}.md;
        cat $f | sed --regexp-extended
            -e '0,/^ +/{s/^ +/# /}'
            -e 's/^ {1,3}([^ ])/\1/'
            -e '/^[0-9]+\. +http/! s/^([0-9]+\. )/## \1/'
            -e 's/^([0-9]+\.[0-9]+\. )/### \1/'
            -e 's/^([0-9]+\.[0-9]+\.[0-9]+\. )/#### \1/'
            -e 's/^([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+\. )/##### \1/'
            > $md;
        printf "\n---\n\noriginal source\x3a [$f](https://gitweb.torproject.org/torspec.git/tree/$f)\n" >> $md;
        title=`sed -En '0,/^# /s/^# (.*)/\1/p' $md`;
        mkdir content/$name;
        printf "<li><a href=\"${name}.html\"><tt>$name</tt>&colon; $title</a></li>" >> content/contents.lr;
        lr=content/$name/contents.lr;
        printf "title\x3a $title\n---\nbody:\n\n" > $lr;
        cat $md >> $lr;
      done
  artifacts:
    paths:
    - public
  only:
    - master
